# action.yml
name: 'Libre DevOps - Run pulumi for Azure -  GitHub Action'
description: 'The heavily opinionated Libre DevOps Action to run pulumi, pulumi-compliance, tfsec and checkov, targetting Azure.'
author: "Craig Thacker <craig@craigthacker.dev>"
branding:
  icon: 'terminal'
  color: 'green'

inputs:
  pulumi-path:
    description: 'The absolute path in Linux format to your pulumi code'
    required: true

  pulumi-workspace-name:
    description: 'The name of a pulumi workspace, should be in plain text string'
    required: true

  pulumi-backend-storage-rg-name:
    description: 'The name of resource group your storage account exists in,  needed for state file storage'
    required: true

  pulumi-backend-storage-account-name:
    description: 'The name of your storage account , needed for state file storage'
    required: true

  pulumi-backend-blob-container-name:
    description: 'The name of your storage account blob container, needed for state file storage'
    required: true

  pulumi-backend-storage-access-key:
    description: 'The key to access your storage account, needed for state file storage'
    required: true

  pulumi-backend-state-name:
    description: 'The name of your statefilee, needed for state pulumi'
    required: true

  pulumi-provider-client-id:
    description: 'The client ID for your service principal, needed to authenticate to your tenant'
    required: true

  pulumi-provider-client-secret:
    description: 'The client secret for your service principal, needed to authenticate to your tenant'
    required: true

  pulumi-provider-subscription-id:
    description: 'The subscription id of the subscription you wish to deploy to, needed to authenticate to your tenant'
    required: true

  pulumi-provider-tenant-id:
    description: 'The tenant id of which contains subscription you wish to deploy to, needed to authenticate to your tenant'
    required: true

  pulumi-compliance-path:
    description: 'The path to your pulumi-compliance policies, should be a local path or passed as git: etc'
    required: true

  checkov-skipped-tests:
    description: 'The CKV codes you wish to skip, if any.'
    required: true
    default: ""

  run-pulumi-destroy:
    description: 'Do you want to run pulumi destroy? - Set to true to trigger pulumi plan -destroy'
    required: true
    default: "false"
    
  run-pulumi-plan-only:
    description: 'Do you only want to run pulumi plan & never run the apply or apply destroy? - Set to true to trigger pulumi plan only.'
    required: true
    default: "true"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pulumi-path }}
    - ${{ inputs.pulumi-workspace-name }}
    - ${{ inputs.pulumi-backend-storage-rg-name }}
    - ${{ inputs.pulumi-backend-storage-account-name }}
    - ${{ inputs.pulumi-backend-blob-container-name }}
    - ${{ inputs.pulumi-backend-storage-access-key }}
    - ${{ inputs.pulumi-backend-state-name }}
    - ${{ inputs.pulumi-provider-client-id }}
    - ${{ inputs.pulumi-provider-client-secret }}
    - ${{ inputs.pulumi-provider-subscription-id }}
    - ${{ inputs.pulumi-provider-tenant-id }}
    - ${{ inputs.pulumi-compliance-path }}
    - ${{ inputs.checkov-skipped-tests }}
    - ${{ inputs.run-pulumi-destroy }}
    - ${{ inputs.run-pulumi-plan-only }}
